---

name: ci

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04

    timeout-minutes: 15

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Download Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.8.0-linux-amd64 > bin/test-reporter
          chmod +x bin/test-reporter

      - name: Configure bundler
        run: |
          echo "BUNDLE_GEMFILE=Gemfile" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$(pwd)/vendor/bundle" >> $GITHUB_ENV

      - name: Enable coverage tracking
        run: echo "COVERAGE=true" >> $GITHUB_ENV

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler: none

      - name: Install a specific rubygems version
        run: gem update --system 3.1.4

      - name: Install a specific bundler version
        run: gem install bundler -v 2.2.0.rc.2

      - name: Cat current Gemfile to a specific file so caching works
        run: cat "$BUNDLE_GEMFILE.lock" > current_gemfile.lock

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: gems-2.7.2-rails_60-${{ hashFiles('current_gemfile.lock') }}

      - name: Install dependencies
        run: bundle install --jobs 3

      - name: Setup git
        run: |
          git config --global user.email activeadmin@ci.dummy
          git config --global user.name ActiveAdmin

      - name: Run lints
        run: bin/rake lint

      - name: Format coverage
        run: |
          bin/prepare_coverage
          bin/test-reporter format-coverage --output coverage/codeclimate.lint.json

      - name: Save partial coverage as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/codeclimate.lint.json

  test:
    runs-on: ubuntu-20.04

    timeout-minutes: 15

    strategy:
      fail-fast: false

      matrix:
        ruby: [2.7.1, 2.6.6]

        deps: ["rails_52", "rails_60", "rails_60_turbolinks", "rails_60_webpacker"]

        include:
          - ruby: 2.5.8
            deps: rails_52

          - ruby: 2.5.8
            deps: rails_60

          - ruby: jruby-9.2.13.0
            deps: rails_52

          - ruby: jruby-9.2.13.0
            deps: rails_60

    steps:
      - uses: actions/checkout@v2

      - name: Download Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.8.0-linux-amd64 > bin/test-reporter
          chmod +x bin/test-reporter

      - name: Configure bundler (default)
        run: |
          echo "BUNDLE_GEMFILE=Gemfile" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$(pwd)/vendor/bundle" >> $GITHUB_ENV
        if: matrix.deps == 'rails_60'

      - name: Configure bundler (alternative)
        run: |
          echo "BUNDLE_GEMFILE=gemfiles/${{ matrix.deps }}/Gemfile" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$(pwd)/gemfiles/${{ matrix.deps }}/vendor/bundle" >> $GITHUB_ENV
        if: matrix.deps != 'rails_60'

      - name: Set jruby opts
        run: echo "JRUBY_OPTS='-J-Xmx1024m --dev'" >> $GITHUB_ENV
        if: startsWith(matrix.ruby, 'jruby')

      - name: Enable coverage tracking
        run: echo "COVERAGE=true" >> $GITHUB_ENV
        if: "!startsWith(matrix.ruby, 'jruby')"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Install a specific rubygems version
        run: gem update --system 3.1.4

      - name: Install a specific bundler version
        run: gem install bundler -v 2.2.0.rc.2

      - name: Cat current Gemfile to a specific file so caching works
        run: cat "$BUNDLE_GEMFILE.lock" > current_gemfile.lock

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: gems-${{ matrix.ruby }}-${{ matrix.deps }}-${{ hashFiles('current_gemfile.lock') }}

      - name: Install dependencies
        run: bundle install --jobs 3

      - name: Setup git
        run: |
          git config --global user.email activeadmin@ci.dummy
          git config --global user.name ActiveAdmin

      - name: Create test app
        run: bin/rake setup

      - name: Restore cached RSpec runtimes
        uses: actions/cache@v2
        with:
          path: tmp/parallel_runtime_rspec.log
          key: runtimes-rspec-${{ matrix.ruby }}-${{ matrix.deps }}-${{ hashFiles('tmp/parallel_runtime_rspec.log') }}

      - name: Run RSpec tests
        run: |
          PARALLEL_TEST_HEARTBEAT_INTERVAL=3600 bin/parallel_rspec spec/
          RSPEC_FILESYSTEM_CHANGES=true bin/rspec

      - name: Restore cached cucumber runtimes
        uses: actions/cache@v2
        with:
          path: tmp/parallel_runtime_cucumber.log
          key: runtimes-cucumber-${{ matrix.ruby }}-${{ matrix.deps }}-${{ hashFiles('tmp/parallel_runtime_cucumber.log') }}

      - name: Run Cucumber features
        run: |
          PARALLEL_TEST_HEARTBEAT_INTERVAL=3600 bin/parallel_cucumber features/
          bin/cucumber --profile filesystem-changes
          bin/cucumber --profile class-reloading

      - name: Format coverage
        run: |
          bin/prepare_coverage
          bin/test-reporter format-coverage --output coverage/codeclimate.${{ matrix.ruby }}.${{ matrix.deps }}.json
        if: "!startsWith(matrix.ruby, 'jruby')"

      - name: Save partial coverage as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/codeclimate.${{ matrix.ruby }}.${{ matrix.deps }}.json
        if: "!startsWith(matrix.ruby, 'jruby')"

  upload_coverage:
    runs-on: ubuntu-20.04

    needs:
      - lint
      - test

    env:
      CC_TEST_REPORTER_ID: 8d5fcf7abea6d56c625104a9d1a81140a588a7f546f4fa9de9bc6ffc8feaaf70

    steps:
      - name: Download Code Climate test-reporter
        run: |
          mkdir bin
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.8.0-linux-amd64 > bin/test-reporter
          chmod +x bin/test-reporter

      - name: Download partial coverages
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Upload coverage results to Code Climate
        run: |
          bin/test-reporter sum-coverage coverage/codeclimate.*.json
          bin/test-reporter upload-coverage
